
package com.seguridadsesion.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ApiServiceHelperImplService", targetNamespace = "http://webservice.seguridadsesion.com/", wsdlLocation = "http://localhost:8080/WS/ApiServiceHelper?wsdl")
public class ApiServiceHelperImplService
    extends Service
{

    private final static URL APISERVICEHELPERIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.seguridadsesion.webservice.ApiServiceHelperImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.seguridadsesion.webservice.ApiServiceHelperImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/WS/ApiServiceHelper?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/WS/ApiServiceHelper?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        APISERVICEHELPERIMPLSERVICE_WSDL_LOCATION = url;
    }

    public ApiServiceHelperImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApiServiceHelperImplService() {
        super(APISERVICEHELPERIMPLSERVICE_WSDL_LOCATION, new QName("http://webservice.seguridadsesion.com/", "ApiServiceHelperImplService"));
    }

    /**
     * 
     * @return
     *     returns ApiServiceHelper
     */
    @WebEndpoint(name = "ApiServiceHelperImplPort")
    public ApiServiceHelper getApiServiceHelperImplPort() {
        return super.getPort(new QName("http://webservice.seguridadsesion.com/", "ApiServiceHelperImplPort"), ApiServiceHelper.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApiServiceHelper
     */
    @WebEndpoint(name = "ApiServiceHelperImplPort")
    public ApiServiceHelper getApiServiceHelperImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.seguridadsesion.com/", "ApiServiceHelperImplPort"), ApiServiceHelper.class, features);
    }

}
