
package com.seguridadsesion.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ApiServiceHelper", targetNamespace = "http://webservice.seguridadsesion.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApiServiceHelper {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://webservice.seguridadsesion.com/", className = "com.seguridadsesion.webservice.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webservice.seguridadsesion.com/", className = "com.seguridadsesion.webservice.LoginResponse")
    public String login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
